name: plastico_bolha
description: Bubble Tycoon Idle Game.
publish_to: 'none'
version: 1.2.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Ícones Padrão ---
  cupertino_icons: ^1.0.2

  # --- Suas Bibliotecas (Limpo e Sem Duplicatas) ---
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.0
  google_mobile_ads: ^5.0.0
  audioplayers: ^5.2.1
  soundpool: ^2.4.1  # <-- O NOVO MOTOR DE ÁUDIO

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # --- Seus Assets ---
  assets:
    - assets/audio/
    - assets/images/
