name: plastico_bolha
description: Bubble Tycoon Idle Game.
publish_to: 'none'
version: 1.4.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Ícones ---
  cupertino_icons: ^1.0.2

  # --- Bibliotecas ---
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.0
  google_mobile_ads: ^5.0.0
  
  # --- O MOTOR DE ÁUDIO "FERRARI" ---
  flutter_soloud: ^3.2.5
  
  # --- PAGAMENTOS PLAY STORE ---
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/images/

# --- Ícones ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
