name: PlasticoBolha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vibration: ^3.1.5
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.0
  google_mobile_ads: ^7.0.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
